#!/usr/bin/python

import sys
import os
import json
import requests
import time

from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

from bs4 import BeautifulSoup
from argparse import ArgumentParser

def load_type(t):

    return '{}: '.format(t.capitalize())

def banner():

    banner_str = '''
 _______  _______  __   __  ___      ___      _______
|       ||       ||  | |  ||   |    |   |    |   _   |
|  _____||       ||  |_|  ||   |    |   |    |  |_|  |
| |_____ |       ||       ||   |    |   |    |       |
|_____  ||      _||_     _||   |___ |   |___ |       |
 _____| ||     |_   |   |  |       ||       ||   _   |
|_______||_______|  |___|  |_______||_______||__| |__|
    '''

    print(banner_str)

def main():

    parser = ArgumentParser(description='scylla.sh CLI tool')

    parser.add_argument('-o', '--offset', help='record start offset value (default is 0)', default='0')
    parser.add_argument('-c', '--count', help='number of records to retrieve (default is 500)', default='500')
    parser.add_argument('-q', '--query', help='query')
    parser.add_argument('-t', '--type', help='type', default='email')
    parser.add_argument('-v', '--verbose', help='Increase verbosity')
    parser.add_argument('-s', '--save', help='Save Scylla results to output file')
    parser.add_argument('-l', '--lookup', help='Lookup plain text for hash online', action='store_true', default=False)

    args = parser.parse_args()

    count = args.count
    offset = args.offset
    type = args.type
    query = args.query
    lookup = args.lookup
    save_file = args.save
    verbose = args.verbose

    url = 'https://scylla.sh/search?q={}+{}&from={}&size={}'.format(load_type(type), query, offset, count)

    print '[*] Searching scylla.sh for leaked {} credentials...'.format(query)

    r = requests.get(url, headers={'Accept': 'application/json'}, verify=False)
    c = r.status_code

    if c == 500:
        print '[-] Got back an Internal Server Error, which means the server is potentially down. Try again momentarily, or use a browser to issue the following request if possible:'
        print '{}\n'.format(url)

    if c == 200:

        records = r.json()
        print '[+] {} records found!\n'.format(len(records))

        if save_file:
            with open(save_file, 'w') as write_json_records:
                write_json_records.write(json.dumps(records, indent=2))

            print '[+] Records saved to {}\n'.format(save_file)

        time.sleep(1)


        for record in records:
            rkeys = record['_source'].keys()

            for obj in sorted(list(set(rkeys))):
                try:
                    output_line = '{0:10}: {1:5}'.format(obj.encode('utf-8'), record['_source'][obj].encode('utf-8'))

                except:
                    output_line = '{0:10}: {1:5}'.format(obj, record['_source'][obj])

if __name__ == '__main__':

    banner()
    main()
